lib/texting_web/router.ex
defmodule TextingWeb.Router do
  use TextingWeb, :router

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TextingWeb.Plugs.Locale)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :dashboard do
    plug(TextingWeb.Plugs.LoadUser)
    plug(TextingWeb.Plugs.DashboardLayout)
    plug(TextingWeb.Plugs.FetchRecipients)
  end

  pipeline :help do
    plug(TextingWeb.Plugs.HelpLayout)
  end

  pipeline :casestudy do
    plug(TextingWeb.Plugs.CaseStudyLayout)
  end

  pipeline :loaduser do
    plug(TextingWeb.Plugs.LoadUser)
  end

  pipeline :admin do
    plug(TextingWeb.Plugs.AuthorizeAdmin)
  end

  scope "/dashboard/admin", TextingWeb.Dashboard.Admin do
    pipe_through([:browser, :dashboard, :admin])

    get("/customers", CustomerController, :index)
    get("/customers/:id", CustomerController, :show)
    get("/customers/:id/edit", CustomerController, :edit)
    put("/customers/:id/edit", CustomerController, :update)
    get("/customers/campaign/:id", CampaignAdminController, :index)
  end

  scope "/", TextingWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    post("/", PageController, :create)
    get("/privacy-policy", PrivacyController, :index)
    get("/terms-conditions", TermsController, :index)

    # Sign in and out
    get("/sign-in", AuthController, :new, as: :sign_in)
    get("/sign-in/confirm-email/", AuthController, :confirm_email, as: :sign_in)
    post("/sign-in", AuthController, :new, as: :sign_in)
    get("/sign-out", AuthController, :delete, as: :sign_out)
    get("/sign-in/:token", AuthController, :create, as: :sign_in)
    get("/sign-up", UserController, :new, as: :sign_up)
    post("/sign-up", UserController, :create, as: :sign_up)

    get("/confirm-email", ConfirmEmailController, :new)
    post("/confirm-email", ConfirmEmailController, :create)
  end

  # Tutorial and Help
  scope "/help", TextingWeb.Help do
    pipe_through([:browser, :help])
    get("/", HelpController, :index)
    get("/how-to-start-a-campaign", StartCampaignController, :index)
    get("/how-to-upload-contact", UploadContactController, :index)
    get("/how-to-use-analytics", HowToUseAnalyticsController, :index)
  end

  # Case study
  scope "/case-study", TextingWeb.CaseStudy do
    pipe_through([:browser, :casestudy])

    get("/churches", ChurchController, :index)
  end

  scope "/", TextingWeb do
    pipe_through([:browser, :loaduser])

    get("/phoneverify", PhoneVerifyController, :new)
    post("/phoneverify", PhoneVerifyController, :create)
    get("/codeverify", CodeVerifyController, :new)
    post("/codeverify", CodeVerifyController, :create)
  end

  scope "/dashboard", TextingWeb.Dashboard do
    pipe_through([:browser, :dashboard])

    get("/campaign", CampaignController, :index)

    get("/contact", ContactUsController, :index)
    post("/contact", ContactUsController, :create)

    get("/", DashboardController, :new)

    post("/add-to-recipients", RecipientController, :add)
    get("/recipients/", RecipientController, :show)
    delete("/recipients/:id", RecipientController, :delete)
    post("/recipients/delete", RecipientController, :delete_selected)

    get("/checkout/sms", CheckoutSmsController, :show_sms)
    put("/checkout/sms", CheckoutSmsController, :preview_sms)
    post("/checkout/sms/shorten", CheckoutSmsController, :create_short_link)

    # put "/checkout/sms/confirm", CheckoutSmsController, :confirm_sms
    get("/checkout/sms/preview", CheckoutSmsPreviewController, :index)
    post("/checkout/sms/preview", CheckoutSmsPreviewController, :send_sms)

    get("/checkout/mms", CheckoutMmsController, :show_mms)
    post("/checkout/mms", CheckoutMmsController, :preview_mms)
    get("/checkout/mms/preview", CheckoutMmsPreviewController, :index)
    # put "/checkout/mms/confirm", CheckoutMmsController, :confirm_mms
    post("/checkout/mms/preview", CheckoutMmsPreviewController, :send_mms)

    get("/campaign/history", CampaignHistoryController, :index)
    get("/campaign/history/:id", CampaignHistoryController, :show)

    get("/buy-credit", BuyCreditController, :index)
    post("/buy-credit", BuyCreditController, :create)

    get("/payment", PaymentController, :new)
    post("/payment", PaymentController, :create)

    get("/plan", PlanController, :index)
    post("/plan", PlanController, :create)
    post("/plan/cancel", PlanController, :delete)

    get("/upload-contact", UploadContactController, :new)
    post("/upload-contact", UploadContactController, :upload)

    get("/billing", BillingInfoController, :new)
    post("/billing", BillingInfoController, :create)
    delete("/billing/:id", BillingInfoController, :delete_card)
    post("/billing/change/default-card/:id", BillingInfoController, :make_default_card)

    get("/invoice", InvoiceController, :index)

    get("/analytics", AnalyticsController, :index)

    get("/phonenumbers", PhonenumberController, :new)

    get("/account-info", AccountInfoController, :index)
    get("/account-info/:id", AccountInfoController, :edit)
    put("/account-info", AccountInfoController, :update)

    get("/account-info-welcome-message", AccountInfoController, :new_welcome_message)
    post("/account-info-welcome-message", AccountInfoController, :create_welcome_message)
    get("/account-info-welcome-message/edit", AccountInfoController, :edit_welcome_message)
    put("/account-info-welcome-message", AccountInfoController, :update_welcome_message)

    resources "/phonebooks", PhonebookController do
      resources("/people", PersonController, except: [:index])
    end

    # CSV Export
    get("/csv/:id", CsvExportController, :export)
  end

  # scope "/auth", TextingWeb do
  #   pipe_through :browser

  #   get "/:provider", AuthController, :request
  #   get "/:provider/callback", AuthController, :callback
  #   post "/:provider/callback", AuthController, :callback
  # end

  # Other scopes may use custom stacks.
  scope "/api", TextingWeb do
    pipe_through(:api)

    # Stripe Webhook
    # post "/planchanged", StripeWebhookController, :handle_invoiceitem_created
    # post "/subscription-canceled", StripeWebhookController, :handle_subscription_deleted
    post("/invoice-payment-succeeded", StripeWebhookController, :handle_invoice_payment_succeeded)
    # post "/charge-succeeded", StripeWebhookController, :handle_charge_succeeded

    # Twilio Webhook
    post("/message-incoming", TwilioWebhookController, :message_incoming)
    post("/message-status", TwilioWebhookController, :message_status)
  end
end

lib/texting_web/controllers/case_study/church_controller.ex
defmodule TextingWeb.CaseStudy.ChurchController do
  use TextingWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/texting_web/views/case_study/church_view.ex
defmodule TextingWeb.CaseStudy.ChurchView do
  use TextingWeb, :view
end

lib/texting_web/templates/case_study/church/index.html.eex
<div class="help-content">
  <div class="row">
    <div class="col-sm-12">
      <h2 class="help-header">성도랑 소통하는 가장 좋은 방법</h2>
      <h4 style="text-align: center; margin-bottom: 50px;">Texty marketing provides very simple way to get you started.
        First <a href="<%= sign_in_path(@conn, :new) %>" target="_blank">sign in to dashboard</a>
        (Not a member? <a href="<%= sign_up_path(@conn, :new) %>" target="_blank"> sign up for free</a> ).
      </h4>

      <img src="<%= static_path(@conn, "/images/casestudy/church.jpg") %>" class="casestudy-images" alt="">

      <p class="casestudy-desc">먼저 Texty Marketing을 소개해 드리겠습니다.

        텍스티 마케팅은, 회사, 단체, 교회의 소식을 고객들이나 직원 또는 교인들에게
        핸드폰 문자(sms) 메세지 또는 이미지(mms) 메세지를 이용해서 단체 메세지를 전송하는 웹 기반 플랫폼 마케팅 회사입니다.

        더욱 간단히 설명하자면, 단체 알림 문자 시스템입니다.
      </p>
      <img src="<%= static_path(@conn, "/images/casestudy/intro.jpg") %>" class="casestudy-images" alt="">

      <p class="casestudy-desc">Texty Marketing의 적용 사례</p>
      <img src="<%= static_path(@conn, "/images/casestudy/screenshot.png") %>"
      class="casestudy-images"
      alt="">

      <p class="casestudy-desc">
        <span style="font-weight: bold; font-style: italic; color: blueviolet; font-size: 20px; ">첫번째 적용사례는 교회소식을 단체문자를
          통해서 알리는 것입니다.</span><br>
        <br> 요즘 성도들은 보통 일주일에 한번 주일 예배를 참석해서 주보를 통해 교회의 소식이나 중요한 행사에 대한 소식을 접하게 되는 경우가 많습니다. <br>
        평일에는 보통 그런 소식들이나 행사소식을 잊어버리기 쉽습니다.
        그래서 보통 전화심방으로 알리기도 하며, 요즘에 가장 많이 쓰는 카카오톡으로 개인에게 알리거나 단체 카카오 채팅방을 만들어서 알리기도 합니다.
        <br><br>
        하지만 일일이 전화하거나 따로 문자나 카카오톡을 보내는 방법에는 그 수에 한계가 있고 시간의 효율성에 있어서 적합하지 않습니다.
        또한 카카오톡을 이용해서 소식을 알리는 방법에는 여러 불편한 점이 있습니다. <br><br>

        <span style="font-weight: bold;">첫번째</span>는 보내는 사람이 일일이 한사람 한사람 선택해서 대화창을 만들어서 같은 내용을 복사해서 붙여 넣기를 해야하는 불편함,<br>
        <span style="font-weight: bold;">두번째</span>는 단체 카카오 채팅방을 만들게되면 여러명이 한방에 있게 됨으로 인해서 원치 않는 메세지를 받게 될수도 (다른 사람의
        대답을 듣게 되는 경우) 있고,
        <br>
        <span style="font-weight: bold;">세번째</span>는 단체로 메세지를 보내는 양도 제한되 있어서 너무 많은 사람을 초대해서 메세지를 보내게 되면 일정기간동안 카카오톡이
        정지될 수 있습니다.
        <br><br>

        <span style="font-weight: bold; font-style: italic; color:darkcyan;">하지만 텍스티 마케팅 서비스를 사용하시게 되면 이 모든것이 아주 쉽게
          해결됩니다.</span>
        <br><br>
        1. 핸드폰 기본 기능인 문자(sms) 또는 이미지(mms) 메세지 서비스를 사용하기 때문에 특별한 앱의 제한(다른앱을 설치하지 않고서도) 없이 사용하실 수 있습니다.
        <br>
        2. 누구나 핸드폰을 소지하고 있고 수시로 확인하기 때문에 소식 전달하기에 가장 효율적입니다.
        <br>
        3. 수신자의 숫자에 제한을 받지 않습니다.
        <br>
        4. 수신자의 핸드폰으로 개별적으로 전송되기 때문에 단체 카카오 채팅방에서 발견되는 산만한 채팅방의 단점이 없습니다.
        <br>
        5. 문자에 인터넷 링크도 포함시킬수 있고 또한 사진도 첨부해서 보내실 수 있습니다.
        <br><br>

        <span style="font-weight: bold; font-style: italic; color: blueviolet; font-size: 20px;">두번째 적용 사례는 텍스티 마케팅
          서비스를 이용해서 목사님의
          설교링크를 보내는 것입니다.</span> <br><br>
        대부분의 교회가 목사님의 귀한 설교를 교회 홈페이지나 Youtube에 올립니다. <br>
        하지만 중요한것은 대부분의 사람들은 그 설교링크를 직접 입력하고 찾아가서 보질 않습니다. <br>
        번거롭다고 생각하기 때문입니다. 하지만 설교링크를 문자메세지로 보내면 어떻게 될까요? <br>
        많은 사람들이 아주 쉽게 목사님의 귀한 설교를 아무때나 접할 수 있습니다. <br>
        <br><br>

        <span style="font-weight: bold; font-style: italic; color:darkcyan;">텍스티 마케팅 서비스의 실제 사례를 요점하면 이렇습니다.</span>
        <br><br>
        1. 성도들에게 교회 소식과 행사소식을 빠른 시간 안에 알린다. <br>

        2. 목사님의 설교링크를 문자 메세지로 바로 보내서 성도들이 원할때 언제든지 볼수 있게 한다. <br><br>


        지금 당장 www.texty.marketing 접속하셔서 무료로 가입하셔서 100개 크레딧을 무료로 받으시고 직접 체험해 보시길 바랍니다. <br>

        또한 지금 현재 무료 컨설팅과 무료 셋업을 진행중이니 이 좋은 기회를 놓치지 마시고 info@texty.marketing 또는 (213) 884 - 8790 으로 연락 바랍니다.

      </p>
      <br><br><br>
    </div>
  </div>
</div>