lib/texting_web/router.ex
defmodule TextingWeb.Router do
  use TextingWeb, :router

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TextingWeb.Plugs.Locale)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :dashboard do
    plug(TextingWeb.Plugs.LoadUser)
    plug(TextingWeb.Plugs.DashboardLayout)
    plug(TextingWeb.Plugs.FetchRecipients)
  end

  pipeline :help do
    plug(TextingWeb.Plugs.HelpLayout)
  end

  pipeline :casestudy do
    plug(TextingWeb.Plugs.CaseStudyLayout)
  end

  pipeline :loaduser do
    plug(TextingWeb.Plugs.LoadUser)
  end

  pipeline :admin do
    plug(TextingWeb.Plugs.AuthorizeAdmin)
  end

  scope "/dashboard/admin", TextingWeb.Dashboard.Admin do
    pipe_through([:browser, :dashboard, :admin])

    get("/customers", CustomerController, :index)
    get("/customers/:id", CustomerController, :show)
    get("/customers/:id/edit", CustomerController, :edit)
    put("/customers/:id/edit", CustomerController, :update)
    get("/customers/campaign/:id", CampaignAdminController, :index)
  end

  scope "/", TextingWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    post("/", PageController, :create)
    get("/privacy-policy", PrivacyController, :index)
    get("/terms-conditions", TermsController, :index)

    # Sign in and out
    get("/sign-in", AuthController, :new, as: :sign_in)
    get("/sign-in/confirm-email/", AuthController, :confirm_email, as: :sign_in)
    post("/sign-in", AuthController, :new, as: :sign_in)
    get("/sign-out", AuthController, :delete, as: :sign_out)
    get("/sign-in/:token", AuthController, :create, as: :sign_in)
    get("/sign-up", UserController, :new, as: :sign_up)
    post("/sign-up", UserController, :create, as: :sign_up)

    get("/confirm-email", ConfirmEmailController, :new)
    post("/confirm-email", ConfirmEmailController, :create)
  end

  # Tutorial and Help
  scope "/help", TextingWeb.Help do
    pipe_through([:browser, :help])
    get("/", HelpController, :index)
    get("/how-to-start-a-campaign", StartCampaignController, :index)
    get("/how-to-upload-contact", UploadContactController, :index)
    get("/how-to-use-analytics", HowToUseAnalyticsController, :index)
  end

  # Case study
  scope "/case-study", TextingWeb.CaseStudy do
    pipe_through([:browser, :casestudy])

    get("/churches", ChurchController, :index)
  end

  scope "/", TextingWeb do
    pipe_through([:browser, :loaduser])

    get("/phoneverify", PhoneVerifyController, :new)
    post("/phoneverify", PhoneVerifyController, :create)
    get("/codeverify", CodeVerifyController, :new)
    post("/codeverify", CodeVerifyController, :create)
  end

  scope "/dashboard", TextingWeb.Dashboard do
    pipe_through([:browser, :dashboard])

    get("/campaign", CampaignController, :index)

    get("/contact", ContactUsController, :index)
    post("/contact", ContactUsController, :create)

    get("/", DashboardController, :new)

    post("/add-to-recipients", RecipientController, :add)
    get("/recipients/", RecipientController, :show)
    delete("/recipients/:id", RecipientController, :delete)
    post("/recipients/delete", RecipientController, :delete_selected)

    get("/checkout/sms", CheckoutSmsController, :show_sms)
    put("/checkout/sms", CheckoutSmsController, :preview_sms)
    post("/checkout/sms/shorten", CheckoutSmsController, :create_short_link)

    # put "/checkout/sms/confirm", CheckoutSmsController, :confirm_sms
    get("/checkout/sms/preview", CheckoutSmsPreviewController, :index)
    post("/checkout/sms/preview", CheckoutSmsPreviewController, :send_sms)

    get("/checkout/mms", CheckoutMmsController, :show_mms)
    post("/checkout/mms", CheckoutMmsController, :preview_mms)
    get("/checkout/mms/preview", CheckoutMmsPreviewController, :index)
    # put "/checkout/mms/confirm", CheckoutMmsController, :confirm_mms
    post("/checkout/mms/preview", CheckoutMmsPreviewController, :send_mms)

    get("/campaign/history", CampaignHistoryController, :index)
    get("/campaign/history/:id", CampaignHistoryController, :show)

    get("/buy-credit", BuyCreditController, :index)
    post("/buy-credit", BuyCreditController, :create)

    get("/payment", PaymentController, :new)
    post("/payment", PaymentController, :create)

    get("/plan", PlanController, :index)
    post("/plan", PlanController, :create)
    post("/plan/cancel", PlanController, :delete)

    get("/upload-contact", UploadContactController, :new)
    post("/upload-contact", UploadContactController, :upload)

    get("/billing", BillingInfoController, :new)
    post("/billing", BillingInfoController, :create)
    delete("/billing/:id", BillingInfoController, :delete_card)
    post("/billing/change/default-card/:id", BillingInfoController, :make_default_card)

    get("/invoice", InvoiceController, :index)

    get("/analytics", AnalyticsController, :index)

    get("/phonenumbers", PhonenumberController, :new)

    get("/account-info", AccountInfoController, :index)
    get("/account-info/:id", AccountInfoController, :edit)
    put("/account-info", AccountInfoController, :update)

    get("/account-info-welcome-message", AccountInfoController, :new_welcome_message)
    post("/account-info-welcome-message", AccountInfoController, :create_welcome_message)
    get("/account-info-welcome-message/edit", AccountInfoController, :edit_welcome_message)
    put("/account-info-welcome-message", AccountInfoController, :update_welcome_message)

    resources "/phonebooks", PhonebookController do
      resources("/people", PersonController, except: [:index])
    end

    # CSV Export
    get("/csv/:id", CsvExportController, :export)
  end

  # scope "/auth", TextingWeb do
  #   pipe_through :browser

  #   get "/:provider", AuthController, :request
  #   get "/:provider/callback", AuthController, :callback
  #   post "/:provider/callback", AuthController, :callback
  # end

  # Other scopes may use custom stacks.
  scope "/api", TextingWeb do
    pipe_through(:api)

    # Stripe Webhook
    # post "/planchanged", StripeWebhookController, :handle_invoiceitem_created
    # post "/subscription-canceled", StripeWebhookController, :handle_subscription_deleted
    post("/invoice-payment-succeeded", StripeWebhookController, :handle_invoice_payment_succeeded)
    # post "/charge-succeeded", StripeWebhookController, :handle_charge_succeeded

    # Twilio Webhook
    post("/message-incoming", TwilioWebhookController, :message_incoming)
    post("/message-status", TwilioWebhookController, :message_status)
  end
end

lib/texting_web/controllers/dashboard/admin/campaign_admin_controller.ex
defmodule TextingWeb.Dashboard.Admin.CampaignAdminController do
  use TextingWeb, :controller
  alias Texting.Sales
  alias Texting.AmazonS3.S3Helpers
  alias Texting.Messenger
  alias Timex
  alias Texting.Helpers
  alias Texting.Bitly
  alias Texting.{Account, Analytics}

  @doc """
  showing campaign history detail
  """
  @one_week 60 * 60 * 24 * 7
  def index(conn, %{"id" => id} = params) do

    order = Sales.get_order_by_order_id(id)
    user = Account.get_user_by_id(order.user_id)
    message_status = Messenger.get_all_message_status(order.id)
    deilvered_count = Analytics.get_delivered_message_status_count(message_status)
		undelivered_count = Analytics.get_undelivered_message_status_count(message_status)
		total_sent = Enum.count(message_status)
    # Get Bitly
    bitly = Bitly.get_bitly_by_order_id(order.id)
    has_bitly = if bitly !== nil do
                  true
                else
                  false
                end
    # Get message status with pagination
    message_status = Messenger.get_message_status_with_pagination(id, params)
    if order.message_type == "mms" do
      current_datetime = Timex.now
      url = case Helpers.compare_datetime(current_datetime, order.media_url_exp) do
              {:expired} ->
                config = S3Helpers.get_aws_s3_config()
                bucket = S3Helpers.get_bucket_name()
                {:ok, url} = S3Helpers.get_presigned_url(config, :get, bucket, order.s3_filename, @one_week)
                media_url_exp = Helpers.add_days_to_current_time(5)
                changeset = Sales.change_order(order, %{"media_url_exp" => media_url_exp, "media_url" => url})
                results = Sales.update_order(changeset)


                url
              {:not_expired} ->
                order.media_url
            end
      render conn, "index.html",
             campaign: order,
             image_url: url,
             message_statuses: message_status,
             bitly: bitly,
             has_bitly: has_bitly,
             has_image: true,
             deilvered_count: deilvered_count,
             undelivered_count: undelivered_count,
             total_sent: total_sent
    else
      render conn, "index.html",
             campaign: order,
             image_url: nil,
             message_statuses: message_status,
             bitly: bitly,
             has_bitly: has_bitly,
             has_image: false,
             deilvered_count: deilvered_count,
             undelivered_count: undelivered_count,
             total_sent: total_sent
    end
  end
end

lib/texting_web/controllers/dashboard/admin/customer_controller.ex
defmodule TextingWeb.Dashboard.Admin.CustomerController do
  use TextingWeb, :controller
  alias Texting.{Admin, Account, Finance, Contact, Sales}

  def index(conn, params) do
    users = Admin.get_all_user(params)
    render conn, "index.html", customers: users
  end

  def show(conn, %{"id" => id} = params) do
    user = Account.get_user_by_id(id)
    stripe_customer = Finance.get_customer(user.stripe.customer_id)
    invoices = Finance.list_invoices(user.id, params)
    charge_history = Finance.list_charge_history(user.id, params)
    #upcoming_invoice = Finance.upcoming_invoice(user.stripe.customer_id)
    phonebook_count = Contact.list_phonebooks(user.id) |> Enum.count
    contact_count = Contact.get_all_people_count(user.id)
    campaigns_history = Sales.get_all_confirmed_status_order_with_pagination(user.id, params)

    case Finance.customer_has_card?(stripe_customer) do
      {:has_card, true} ->
        {default_card_id, cards} = Finance.get_card_info(stripe_customer)
        render conn, "show.html",
          customer: user,
          cards: cards,
          default_card_id: default_card_id,
          has_card: true,
          invoices: invoices,
          charge_history: charge_history,
          # next_billing_date: upcoming_invoice.period_end,
          # amount_due: upcoming_invoice.total,
          phonebook_count: phonebook_count,
          contact_count: contact_count,
          campaigns_history: campaigns_history
      {:no_card, false} ->
        render conn, "show.html",
          customer: user,
          has_card: false,
          invoices: invoices,
          charge_history: charge_history,
          # next_billing_date: upcoming_invoice.period_end,
          # amount_due: upcoming_invoice.total,
          phonebook_count: phonebook_count,
          contact_count: contact_count,
          campaigns_history: campaigns_history
    end

  end

  def edit(conn, %{"id" => id}) do
    user = Account.get_user_by_id(id)
    changeset = Account.change_user(user)

    render conn, "edit.html", customer: user, changeset: changeset
  end

  def update(conn, %{"admin" => params, "id" => id}) do
    user = Account.get_user_by_id(id)
    %{"credits" => credit, "email" => email,
      "first_name" => first_name,
      "last_name" => last_name,
      "phone_number" => phone_number} = params
    user_changeset = Account.change_user(user, %{first_name: first_name,
                                                 last_name: last_name,
                                                 email: email,
                                                 phone_number: phone_number,
                                                 credits: credit})
    Account.update_user(user_changeset)
    conn
    |> redirect(to: customer_path(conn, :index))
  end
end

lib/texting_web/controllers/dashboard/analytics_controller.ex
defmodule TextingWeb.Dashboard.AnalyticsController do
  use TextingWeb, :controller
  alias Texting.{Analytics, Sales, Messenger, Bitly, Contact}

  def index(conn, params) do
    user = conn.assigns.current_user
    orders = Sales.get_all_confirmed_status_order_with_pagination(user.id, params)
    all_contacts = Contact.get_all_people_count(user.id)
    unsubscriber_phonebook = Contact.get_or_create_unsubscribed_contact(user)

    unsubscriber_count = Enum.count(Contact.get_people(unsubscriber_phonebook.id))
    if Enum.empty?(orders) do
      render conn, "index.html",
                    campaigns: [],
                    total_sent: 0,
                    deilvered_count: 0,
                    undelivered_count: 0,
                    total_clicks: 0,
                    recent_campaign: nil,
                    has_campaign: false,
                    all_contacts: all_contacts,
                    unsubscriber_count: unsubscriber_count
    else
      [recent_order] = Enum.take(orders, 1)
      message_status = Messenger.get_all_message_status(recent_order.id)
      total_sent = Enum.count(message_status)
      deilvered_count = Analytics.get_delivered_message_status_count(message_status)
      undelivered_count = Analytics.get_undelivered_message_status_count(message_status)
      bitly = Bitly.get_bitly_by_order_id(recent_order.id)
      # Check if order has bitly link
      total_clicks = Analytics.load_clicks(bitly)
      render conn, "index.html",
                    campaigns: orders,
                    total_sent: total_sent,
                    deilvered_count: deilvered_count,
                    undelivered_count: undelivered_count,
                    total_clicks: total_clicks,
                    recent_campaign: recent_order,
                    has_campaign: true,
                    all_contacts: all_contacts,
                    unsubscriber_count: unsubscriber_count
    end


  end
end

lib/texting_web/controllers/dashboard/billing_info_controller.ex
defmodule TextingWeb.Dashboard.BillingInfoController do
  use TextingWeb, :controller
  alias Texting.Finance

  def new(conn, _params) do
    user = conn.assigns.current_user
    stripe_customer = Finance.get_customer(user.stripe.customer_id)
    stripe_key = System.get_env("STRIPE_PUBLIC_KEY")
    case Finance.customer_has_card?(stripe_customer) do
      {:has_card, true} ->
        {default_card_id, cards} = Finance.get_card_info(stripe_customer)
        render conn, "new.html", cards: cards,
                                 has_card: true,
                                 stripe_key: stripe_key,
                                 default_card_id: default_card_id
      {:no_card, false} ->
        render conn, "new.html", has_card: false, stripe_key: stripe_key
    end
  end

  @doc """
  Add credit card
  """
  def create(conn, %{"stripeToken" => token}) do
    user = conn.assigns.current_user
    case Finance.add_card(user.stripe.customer_id, token) do
      {:ok, message} ->
        conn
        |> put_flash(:info, message)
        |> redirect(to: billing_info_path(conn, :new))
      {:error, message} ->
        conn
        |> put_flash(:error, message)
        |> redirect(to: billing_info_path(conn, :new))
    end
  end

  def delete_card(conn, %{"id" => card_id}) do
    user = conn.assigns.current_user
    case Finance.delete_card(card_id, user.stripe.customer_id) do
      {:ok, message} ->
        conn
        |> put_flash(:info, message)
        |> redirect(to: billing_info_path(conn, :new))
      {:error, message} ->
        conn
        |> put_flash(:error, message)
        |> redirect(to: billing_info_path(conn, :new))
    end
  end

  def make_default_card(conn, %{"id" => card_id}) do
    user = conn.assigns.current_user
    case Finance.update_customer(user.stripe.customer_id, %{default_source: card_id}) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Your default card is updated.")
        |> redirect(to: billing_info_path(conn, :new))
      {:error, _} ->
        conn
        |> put_flash(:error, "Can't make it default. Please try again later.")
        |> redirect(to: billing_info_path(conn, :new))
    end
  end
end

lib/texting_web/controllers/dashboard/campaign_controller.ex
defmodule TextingWeb.Dashboard.CampaignController do
  use TextingWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/texting_web/controllers/dashboard/contact_us_controller.ex
defmodule TextingWeb.Dashboard.ContactUsController do
  use TextingWeb, :controller
  alias Texting.Mailer
  alias TextingWeb.Email


  def index(conn, _params) do
    render conn, "index.html"
  end

  def create(conn, %{"contact_us" => %{"name" => name, "email" => email, "message" => message}} = _params) do

    Email.contact_us_email(email, name, message) |> Mailer.deliver_later
    conn
    |> put_flash(:info, "Thanks for contacting us. We will get back to you within 24 hours.")
    |> redirect(to: contact_us_path(conn, :index))
  end
end

lib/texting_web/controllers/dashboard/csv_export_controller.ex
defmodule TextingWeb.Dashboard.CsvExportController do
  use TextingWeb, :controller
  alias Texting.FileHandler.CsvHandler
  alias Texting.Contact

  def export(conn, %{"id" => phonebook_id}) do
    send_download(
      conn,
      {:binary, export_contacts_from_phonebook(phonebook_id)},
      content_type: "application/csv",
      filename: "contacts.csv"
    )
  end

  def export_contacts_from_phonebook(phonebook_id) do
    Contact.get_people(phonebook_id)
    |> CsvHandler.write()
  end

end

lib/texting_web/templates/dashboard/recipient/scripts.html.eex
<script>
  function checkAll(bx) {
    var cbs = document.getElementsByTagName('input');
    for(var i=0; i < cbs.length; i++) {
      if(cbs[i].type == 'checkbox') {
        cbs[i].checked = bx.checked;
      }
    }
  }

  // Select all delete button using sweetalert2
  var button = document.getElementById("delete-button");
  
  if(button){
    var deleteForm = document.getElementById("delete-form");
    button.addEventListener('click', function(e){
      e.preventDefault();
      console.log("Delete Button Clicked!");
      window.swal({
        title: 'Are you sure?',
        text:  'Remove contacts from Recipients List.',
        showCancelButton: true,
        confirmButtonColor: '#f44336',
        cancelButtonColor:  '#333333',
        confirmButtonText: 'Yes, Delete it!'
        
      }).then((result) => {
        deleteForm.submit();
        if(result.value) {
          window.swal({
            title: 'Deleted!',
            text: 'Your contacts have been removed.',
            timer: 5000,
            type: 'success'
          });
        }
      })
    })
  }
  
  // For each delete button using sweetalert2
//  var buttons = document.querySelectorAll('.delete-each-button');
//  if(buttons.length !== 0) {
//    buttons.forEach(function(button) {
//      button.addEventListener('click', function(e){
//        e.stopPropagation();
//        window.swal({
//          title: 'Are you sure?',
//          text:  'Remove contacts from Recipients List.',
//          showCancelButton: true,
//          confirmButtonColor: '#f44336',
//          cancelButtonColor:  '#333333',
//          confirmButtonText: 'Yes, Delete it!'
//        }).then((result) => {
//          if(result.value) {
//           // $(this).trigger('click');
//          }
//        })
//      })
//    })
//  }

var buttons = document.querySelectorAll('.delete-each-button');
if(buttons.length !== 0) {
  buttons.forEach(function(button) {
    button.addEventListener('phoenix.link.click', function (e) {
      e.stopPropagation();
      console.log("Hello!");
    // window.swal({
    //   title: 'Are you sure?',
    //   text:  'Remove contacts from Recipients List.',
    //   showCancelButton: true,
    //   confirmButtonColor: '#f44336',
    //   cancelButtonColor:  '#333333',
    //   confirmButtonText: 'Yes, Delete it!'
    // }).then((result) => {
    //   if(result.value) {
    //    // $(this).trigger('click');
    //   }
    // })
      
    }, false);
  })
}
 
</script>

lib/texting_web/templates/dashboard/recipient/show.html.eex
  <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
              <div class="card-header card-header-icon" data-background-color="purple">
                    <i class="material-icons">assignment</i>
              </div>

              <div class="card-content">
                    <h2 class="card-title"><%= gettext "Recipients List" %>
                      <span class="header-description"> <%= gettext "You can remove a contact from list or click to send text or image campaign" %></span>
                    </h2>
                    <div class="add-new-button-wrapper">
                        <%= button to: phonebook_path(@conn, :index), method: "get", class: "btn btn-github btn-sm" do %>
                          <i class="material-icons">add</i><%= gettext "Add More" %>
                        <% end %>
                      </div>
                    <%= if Enum.empty?(@recipients.line_items) do %>
                      <p><%= gettext "Your recipients list is empty" %></p>
                    <% else %>
                    <div class="table-wrapper">
                      <div class="table-responsive">
                          <table class="table">
                              <thead>
                                  <tr>
                                    <th><%= gettext "Select All" %></th>
                                    <th><%= gettext "Name" %></th>
                                    <th><%= gettext "Phone Number" %></th>
                                    <th class="text-right"><%= gettext "Actions" %></th>
                                  </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>
                                    <div class="checkbox">
                                      <label>
                                        <input type="checkbox" name="select-all" onclick="checkAll(this)" />
                                      </label>
                                    </div>
                                  </td>
                                </tr>
                                <%= form_for @conn, recipient_path(@conn, :delete_selected), [as: :recipient_delete, id: "delete-form"], fn f -> %>
                                  <%= for recipient <- @page.entries do %>
                                  <tr>
                                      <td>
                                        <div class="checkbox">
                                          <label>
                                            <input type="checkbox" name="recipients_list[]" value="<%= recipient.id %>" />
                                          </label>
                                        </div>
                                      </td>
                                      <td><%= recipient.name %></td>
                                      <td><%= display_phone_number(recipient.phone_number) %></td>

                                      <td class="td-actions text-right">
                                        <%= button to: recipient_path(@conn, :delete, recipient.id), method: "delete", data: [confirm: "Are you sure?"], class: "btn btn-danger delete-each-button" do %>
                                          <i class="material-icons icon-button">close</i><%= gettext "Delete" %>
                                        <% end %>
                                      </td>
                                  </tr>
                                  <% end %>
                                  <tr>
                                      <td><%= submit id: "delete-button", class: "btn btn-danger" do %> <%= gettext "Delete" %> <% end %></td>
                                      <td></td>
                                      <td></td>
                                      <td class="td-actions text-right">
                                        <%= button to: checkout_sms_path(@conn, :show_sms), method: "get", class: "btn btn-primary" do %>
                                          <i class="material-icons icon-button">send</i><%= gettext "Text Campaign" %>
                                        <% end %>
                                        <%= button to: checkout_mms_path(@conn, :show_mms), method: "get", class: "btn btn-primary" do %>
                                          <i class="material-icons icon-button">send</i><%= gettext "Image Campaign" %>
                                        <% end %>
                                       </td>
                                  </tr>
                                <% end %>
                              </tbody>
                          </table>
                          <%= pagination_links @page %>
                      </div>
                    </div>
                    <% end %>
              </div>
            </div>
        </div>
      </div>
    </div>