lib/texting_web/router.ex
defmodule TextingWeb.Router do
  use TextingWeb, :router

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TextingWeb.Plugs.Locale)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :dashboard do
    plug(TextingWeb.Plugs.LoadUser)
    plug(TextingWeb.Plugs.DashboardLayout)
    plug(TextingWeb.Plugs.FetchRecipients)
  end

  pipeline :help do
    plug(TextingWeb.Plugs.HelpLayout)
  end

  pipeline :casestudy do
    plug(TextingWeb.Plugs.CaseStudyLayout)
  end

  pipeline :loaduser do
    plug(TextingWeb.Plugs.LoadUser)
  end

  pipeline :admin do
    plug(TextingWeb.Plugs.AuthorizeAdmin)
  end

  scope "/dashboard/admin", TextingWeb.Dashboard.Admin do
    pipe_through([:browser, :dashboard, :admin])

    get("/customers", CustomerController, :index)
    get("/customers/:id", CustomerController, :show)
    get("/customers/:id/edit", CustomerController, :edit)
    put("/customers/:id/edit", CustomerController, :update)
    get("/customers/campaign/:id", CampaignAdminController, :index)
  end

  scope "/", TextingWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    post("/", PageController, :create)
    get("/privacy-policy", PrivacyController, :index)
    get("/terms-conditions", TermsController, :index)

    # Sign in and out
    get("/sign-in", AuthController, :new, as: :sign_in)
    get("/sign-in/confirm-email/", AuthController, :confirm_email, as: :sign_in)
    post("/sign-in", AuthController, :new, as: :sign_in)
    get("/sign-out", AuthController, :delete, as: :sign_out)
    get("/sign-in/:token", AuthController, :create, as: :sign_in)
    get("/sign-up", UserController, :new, as: :sign_up)
    post("/sign-up", UserController, :create, as: :sign_up)

    get("/confirm-email", ConfirmEmailController, :new)
    post("/confirm-email", ConfirmEmailController, :create)
  end

  # Tutorial and Help
  scope "/help", TextingWeb.Help do
    pipe_through([:browser, :help])
    get("/", HelpController, :index)
    get("/how-to-start-a-campaign", StartCampaignController, :index)
    get("/how-to-upload-contact", UploadContactController, :index)
    get("/how-to-use-analytics", HowToUseAnalyticsController, :index)
  end

  # Case study
  scope "/case-study", TextingWeb.CaseStudy do
    pipe_through([:browser, :casestudy])

    get("/churches", ChurchController, :index)
  end

  scope "/", TextingWeb do
    pipe_through([:browser, :loaduser])

    get("/phoneverify", PhoneVerifyController, :new)
    post("/phoneverify", PhoneVerifyController, :create)
    get("/codeverify", CodeVerifyController, :new)
    post("/codeverify", CodeVerifyController, :create)
  end

  scope "/dashboard", TextingWeb.Dashboard do
    pipe_through([:browser, :dashboard])

    get("/campaign", CampaignController, :index)

    get("/contact", ContactUsController, :index)
    post("/contact", ContactUsController, :create)

    get("/", DashboardController, :new)

    post("/add-to-recipients", RecipientController, :add)
    get("/recipients/", RecipientController, :show)
    delete("/recipients/:id", RecipientController, :delete)
    post("/recipients/delete", RecipientController, :delete_selected)

    get("/checkout/sms", CheckoutSmsController, :show_sms)
    put("/checkout/sms", CheckoutSmsController, :preview_sms)
    post("/checkout/sms/shorten", CheckoutSmsController, :create_short_link)

    # put "/checkout/sms/confirm", CheckoutSmsController, :confirm_sms
    get("/checkout/sms/preview", CheckoutSmsPreviewController, :index)
    post("/checkout/sms/preview", CheckoutSmsPreviewController, :send_sms)

    get("/checkout/mms", CheckoutMmsController, :show_mms)
    post("/checkout/mms", CheckoutMmsController, :preview_mms)
    get("/checkout/mms/preview", CheckoutMmsPreviewController, :index)
    # put "/checkout/mms/confirm", CheckoutMmsController, :confirm_mms
    post("/checkout/mms/preview", CheckoutMmsPreviewController, :send_mms)

    get("/campaign/history", CampaignHistoryController, :index)
    get("/campaign/history/:id", CampaignHistoryController, :show)

    get("/buy-credit", BuyCreditController, :index)
    post("/buy-credit", BuyCreditController, :create)

    get("/payment", PaymentController, :new)
    post("/payment", PaymentController, :create)

    get("/plan", PlanController, :index)
    post("/plan", PlanController, :create)
    post("/plan/cancel", PlanController, :delete)

    get("/upload-contact", UploadContactController, :new)
    post("/upload-contact", UploadContactController, :upload)

    get("/billing", BillingInfoController, :new)
    post("/billing", BillingInfoController, :create)
    delete("/billing/:id", BillingInfoController, :delete_card)
    post("/billing/change/default-card/:id", BillingInfoController, :make_default_card)

    get("/invoice", InvoiceController, :index)

    get("/analytics", AnalyticsController, :index)

    get("/phonenumbers", PhonenumberController, :new)

    get("/account-info", AccountInfoController, :index)
    get("/account-info/:id", AccountInfoController, :edit)
    put("/account-info", AccountInfoController, :update)

    get("/account-info-welcome-message", AccountInfoController, :new_welcome_message)
    post("/account-info-welcome-message", AccountInfoController, :create_welcome_message)
    get("/account-info-welcome-message/edit", AccountInfoController, :edit_welcome_message)
    put("/account-info-welcome-message", AccountInfoController, :update_welcome_message)

    resources "/phonebooks", PhonebookController do
      resources("/people", PersonController, except: [:index])
    end

    # CSV Export
    get("/csv/:id", CsvExportController, :export)
  end

  # scope "/auth", TextingWeb do
  #   pipe_through :browser

  #   get "/:provider", AuthController, :request
  #   get "/:provider/callback", AuthController, :callback
  #   post "/:provider/callback", AuthController, :callback
  # end

  # Other scopes may use custom stacks.
  scope "/api", TextingWeb do
    pipe_through(:api)

    # Stripe Webhook
    # post "/planchanged", StripeWebhookController, :handle_invoiceitem_created
    # post "/subscription-canceled", StripeWebhookController, :handle_subscription_deleted
    post("/invoice-payment-succeeded", StripeWebhookController, :handle_invoice_payment_succeeded)
    # post "/charge-succeeded", StripeWebhookController, :handle_charge_succeeded

    # Twilio Webhook
    post("/message-incoming", TwilioWebhookController, :message_incoming)
    post("/message-status", TwilioWebhookController, :message_status)
  end
end

lib/texting_web/views/layout_view.ex
defmodule TextingWeb.Layout.PageTitle do
  alias TextingWeb.Dashboard.{DashboardView,
                              SmsView,
                              MmsView,
                              PhonebookView,
                              CampaignHistoryView,
                              AnalyticsView,
                              BillingInfoView,
                              InvoiceView,
                              PersonView,
                              RecipientView,
                              CheckoutSmsView,
                              CheckoutSmsPreviewView,
                              CheckoutMmsView,
                              CheckoutMmsPreviewView,
                              BuyCreditView,
                              UploadContactView,
                              PlanView,
                              AccountInfoView,
                              PaymentView,
                              CampaignView,
                              ContactUsView}

  alias TextingWeb.Dashboard.Admin.{CustomerView}
  @app_name "Texty"


  def for({view, action, assigns}) do
    {view, action, assigns}
    |> get()
    |> add_app_name()
  end

  defp get({DashboardView, :new, _}) do
    "Dashboard"
  end

  defp get({SmsView, :index, _}) do
    "Text Campaign"
  end

  defp get({MmsView, :index, _}) do
    "Image Campaign"
  end

  defp get({PhonebookView, :index, _}) do
    "Phonebooks"
  end

  defp get({PhonebookView, :edit, _}) do
    "Phonebooks - Edit"
  end

  defp get({PhonebookView, :new, _}) do
    "Phonebooks - New"
  end

  defp get({PhonebookView, :show, _}) do
    "Phonebooks"
  end

  defp get({PhonebookView, :create, _}) do
    "Phonebooks"
  end

  defp get({PhonebookView, :update, _}) do
    "Phonebooks"
  end

  defp get({PhonebookView, :delete, _}) do
    "Phonebooks"
  end

  defp get({CampaignHistoryView, :index, _}) do
    "Campaign History"
  end

  defp get({CampaignHistoryView, :show, _}) do
    "Campaign History - Details"
  end

  defp get({AnalyticsView, :index, _}) do
    "Analytics"
  end

  defp get({BillingInfoView, :new, _}) do
    "Billing Information"
  end

  defp get({BillingInfoView, :create, _}) do
    "Billing Information"
  end

  defp get({InvoiceView, :new, _}) do
    "Invoices"
  end

  defp get({PersonView, :new, _}) do
    "Contact"
  end

  defp get({PersonView, :edit, _}) do
    "Contact"
  end

  defp get({PersonView, :show, _}) do
    "Contact"
  end

  defp get({PersonView, :create, _}) do
    "Contact"
  end

  defp get({PersonView, :update, _}) do
    "Contact"
  end

  defp get({PersonView, :delete, _}) do
    "Contact"
  end

  defp get({RecipientView, :show, _}) do
    "Recipients"
  end

  defp get({CheckoutSmsView, :show_sms, _}) do
    "Send Text Message"
  end

  defp get({CheckoutSmsView, :preview_sms, _}) do
    "Send Text Message"
  end

  defp get({CheckoutSmsView, :create_short_link, _}) do
    "Send Text Message"
  end

  defp get({CheckoutSmsPreviewView, :index, _}) do
    "Send Text Message - Preview"
  end

  defp get({CheckoutSmsPreviewView, :send_sms, _}) do
    "Send Text Message"
  end

  defp get({CheckoutMmsView, :show_mms, _}) do
    "Send Image Message"
  end

  defp get({CheckoutMmsView, :preview_mms, _}) do
    "Send Image Message"
  end

  defp get({CheckoutMmsPreviewView, :index, _}) do
    "Send Image Message - Preview"
  end

  defp get({CheckoutMmsPreviewView, :send_mms, _}) do
    "Send Image Message"
  end

  defp get({BuyCreditView, :new, _}) do
    "Buy Credit"
  end

  defp get({BuyCreditView, :create, _}) do
    "Buy Credit"
  end

  defp get({UploadContactView, :new, _}) do
    "Upload Contact"
  end

  defp get({UploadContactView, :upload, _}) do
    "Upload Contact"
  end

  defp get({PlanView, :new, _}) do
    "Plan"
  end

  defp get({PlanView, :create, _}) do
    "Plan"
  end

  defp get({AccountInfoView, :index, _}) do
    "Account Information"
  end

  defp get({AccountInfoView, :edit, _}) do
    "Edit Account Information"
  end

  defp get({PaymentView, :new, _}) do
    "Payment Info"
  end

  defp get({PaymentView, :create, _}) do
    "Payment Info"
  end

  defp get({CampaignView, :index, _}) do
    "Start a Campaign"
  end

  defp get({ContactUsView, :index, _}) do
    "Contact Us"
  end

  defp get({CustomerView, :index, _}) do
    "Admin - Customer List"
  end

  defp get({CustomerView, :show, _}) do
    "Admin - Customer Detail"
  end



  defp get(_), do: nil

  defp add_app_name(nil), do: @app_name
  defp add_app_name(title), do: "#{title}"
end

defmodule TextingWeb.LayoutView do
  use TextingWeb, :view
  import TextingWeb.Dashboard.RecipientView, only: [recipient_count: 1]
  alias TextingWeb.Layout.PageTitle

  def page_title(conn) do
    view = view_module(conn)
    action = action_name(conn)
    PageTitle.for({view, action, conn.assigns})
  end

  def switch_locale_path(_conn, locale, language) do
    "<a href=\"?locale=#{locale}\">#{language}</a>" |> Phoenix.HTML.raw()
  end
end

lib/texting_web/templates/layout/_dashboard_sidemenu.html.eex
<div class="sidebar" data-active-color="rose" data-background-color="white" data-image="<%= static_path(@conn, "/images/user-sidemenu-bg.jpg") %>"</div>>
  <!--
      Tip 1: You can change the color of active element of the sidebar using: data-active-color="purple | blue | green | orange | red | rose"
      Tip 2: you can also add an image using data-image tag
      Tip 3: you can change the color of the sidebar with data-background-color="white | black"
  -->

  <div class="logo">
     <!-- <a href="<%= dashboard_path(@conn, :new) %>" class="simple-text logo-mini">

        <img src="<%= static_path(@conn, "/images/l1.png") %>" style="height: 50px;" alt="">

      </a> -->

      <a href="<%= dashboard_path(@conn, :new) %>" class="simple-text logo-normal">
        <img src="<%= static_path(@conn, "/images/t1.png") %>"  style="height: 40px;" alt="">
      </a>
  </div>

  <div class="sidebar-wrapper">
    <div class="user">
			<div class="photo">
				<img src="<%= static_path(@conn, "/images/avatar2.png") %>" alt="User-Profile">
			</div>
			<div class="info">
				<a href="#collapseAccount" data-toggle="collapse" class="collapsed" role="button" aria-expanded="false" aria-controls="collapseAccount">
					<span>
						 <%= @conn.assigns.current_user.first_name %>
							<b class="caret"></b>
					</span>
				</a>
			<!--	<a href="#!email"><span class="white-text email"><%= @conn.assigns.current_user.email %></span></a> -->
				<div class="clearfix"></div>
				<div class="collapse" id="collapseAccount">
					<ul class="nav">
						<li>
							<a href="<%= account_info_path(@conn, :index) %>">
								<span class="sidebar-mini"><i class="material-icons">email_outline</i></span>
								<span class="sidebar-normal"><p> <%= @conn.assigns.current_user.email %></p></span>
							</a>
						</li>
						<li>
							<a href="<%= account_info_path(@conn, :index) %>">
								<span class="sidebar-mini"><i class="material-icons">attach_money</i></span>
								<span class="sidebar-normal"><p> <%= gettext "Credits" %>: <%= @conn.assigns.current_user.credits %></p></span>
							</a>
						</li>
					</ul>


				</div>
			</div>
		</div>

      <ul class="nav">
				<li class="">
					<a href="<%= dashboard_path(@conn, :new) %>">
							<i class="material-icons">apps</i>
							<p> <%= gettext "Dashboard" %> </p>
					</a>
				</li>
				<li class="">
					<a href="<%= campaign_path(@conn, :index) %>">
							<i class="material-icons">send</i>
							<p> <%= gettext "Start campaign" %> </p>
					</a>
				</li>

				<li>
						<a href="<%= campaign_history_path(@conn, :index) %>">
								<i class="material-icons">history</i>
								<p> <%= gettext "Campaign history" %> </p>
						</a>
				</li>
				<li>
					<a href="#collapseContactMenu" data-toggle="collapse" class="collapsed" role="button" aria-expanded="false" aria-controls="collapseAccountMenu">
						<i class="material-icons">contact_phone</i>
						<p><%= gettext "Contacts" %> <b class="caret"></b></p>
					</a>
					<div class="clearfix"></div>
					<div id="collapseContactMenu" class="collapse">
						<ul class="nav">
							<li>
								<a href="<%= phonebook_path(@conn, :index) %>">
										<i class="material-icons">contacts</i>
										<p> <%= gettext "Phonebook" %> </p>
								</a>
							</li>
							<li>
								<a href="<%= upload_contact_path(@conn, :new) %>">
										<i class="material-icons">cloud_upload</i>
										<p> <%= gettext "Upload Contact" %> </p>
								</a>
							</li>
						</ul>
					</div>
				</li>



        <li>
          <a href="<%= analytics_path(@conn, :index) %>">
              <i class="material-icons">assessment</i>
              <p> <%= gettext "Analytics" %> </p>
          </a>
				</li>

				<li>
					<a href="#collapseAccountMenu" data-toggle="collapse" class="collapsed" role="button" aria-expanded="false" aria-controls="collapseAccountMenu">
						<i class="material-icons">account_box</i>
						<p><%= gettext "Account" %> <b class="caret"></b></p>
					</a>
					<div class="clearfix"></div>
					<div id="collapseAccountMenu" class="collapse">
						<ul class="nav">
							<li>
								<a href="<%= account_info_path(@conn, :index) %>">
										<i class="material-icons">account_box</i>
										<p> <%= gettext "Detail" %> </p>
								</a>
							</li>
							<li>
								<a href="<%= billing_info_path(@conn, :new) %>">
										<i class="material-icons">monetization_on</i>
										<p> <%= gettext "Billing Info" %> </p>
								</a>
							</li>
							<li>
								<a href="<%= invoice_path(@conn, :index) %>">
										<i class="material-icons">receipt</i>
										<p> <%= gettext "Invoice" %> </p>
								</a>
							</li>

							<li>
								<a href="<%= plan_path(@conn, :index) %>">
										<i class="material-icons">content_paste</i>
										<p> <%= gettext "Plan" %> </p>
								</a>
							</li>

							<li>
								<a href="<%= buy_credit_path(@conn, :index) %>">
										<i class="material-icons">credit_card</i>
										<p> <%= gettext "Buy Credits" %> </p>
								</a>
							</li>
						</ul>
					</div>
				</li>

				<li>
					<a href="<%= recipient_path(@conn, :show) %>">
							<i class="material-icons">add_shopping_cart</i>
							<p> <%= gettext "Recipients" %> <span class="recipients-notification"><%= recipient_count(@conn) %></span> </p>
					</a>
				</li>

				<li class="">
					<a href="<%= contact_us_path(@conn, :index) %>">
							<i class="material-icons">email</i>
							<p> <%= gettext "Contact us" %> </p>
					</a>
				</li>

				<li class="">
					<a href="<%= help_path(@conn, :index) %>" target="_blank">
							<i class="material-icons">help</i>
							<p> <%= gettext "Help & Tutorials" %> </p>
					</a>
				</li>

        <li class="log-out">
          <a href="/sign-out">
              <i class="material-icons">highlight_off</i>
              <p> <%= gettext "Log out" %> </p>
          </a>
				</li>
				<%= if @conn.assigns.current_user.admin do %>
					<li class="log-out">
						<a href="<%= customer_path(@conn, :index) %>">
								<i class="material-icons">lightbulb_outline</i>
								<p> Admin </p>
						</a>
					</li>
				<% end %>
      </ul>
	</div>

	<div class="sidebar-background"></div>
</div>

lib/texting_web/templates/layout/_dashboard_topmenu.html.eex
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
				<div class="navbar-minimize">
					<button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
							<i class="material-icons visible-on-sidebar-regular">more_vert</i>
							<i class="material-icons visible-on-sidebar-mini">view_list</i>
					</button>
				</div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> <%= page_title(@conn) %> </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

							<div class="dropdown">
								<button href="#pablo" class="dropdown-toggle btn btn-primary btn-block" data-toggle="dropdown"><%= gettext "Choose a language" %> <b class="caret"></b></button>
								<ul class="dropdown-menu dropdown-menu-left">
									<li class="dropdown-header"><%= gettext "Choose a preferred language" %></li>
									<li><%= switch_locale_path(@conn, :en, "English") %></li>
									<li><%= switch_locale_path(@conn, :ko, "Korean") %></li>

								</ul>
							</div>

            </ul>
        </div>
    </div>
  </nav>

lib/texting_web/templates/layout/app_case_study.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="google-site-verification" content="DSGiTI2Lf03gy_18eDtPF_y5wvxEZdsVgUDXef9LnEU" />
  <link rel="shortcut icon" type="image/png" href="<%= static_path(@conn, "/images/favicon.png") %>"/>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125440102-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-125440102-1');
  </script>

  <!-- Google Tag Manager -->
  <script>(function (w, d, s, l, i) {
    w[l] = w[l] || []; w[l].push({
      'gtm.start':
        new Date().getTime(), event: 'gtm.js'
    }); var f = d.getElementsByTagName(s)[0],
      j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-5K96KFG');</script>
  <!-- End Google Tag Manager -->

  <title>Texty Marketing - Help and Tutorials</title>


  <!--<link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ"
    crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">

  <!--  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css"> -->
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css"> -->
  <!-- <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"> -->

  <script src="https://js.stripe.com/v3/"></script>
</head>

<body class="help-body">
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5K96KFG" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <div class="help-wrapper container-fluid">
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="<%= help_path(@conn, :index) %>">
        <img class="help-logo" src="<%=static_path(@conn, "/images/t5.png") %>" alt="Texty Logo">
      </a>
    </nav>
    <div class="container">
      <div class="jumbotron">
        <h1 class="display-4">Case Study</h1>
        <p class="lead">Here is list that explains how business can use Text marketing.</p>
        <hr class="my-4">
        <p class="jumbo-description">Are you not a member of texty marketing? Why don't you start now and get 100
          credits for free?</p>
        <a class="btn btn-primary btn-lg" href="<%= sign_up_path(@conn, :new) %>" role="button">Get 100 Credits for
          free</a>
        <a class="btn btn-github btn-lg" href="<%= help_path(@conn, :index) %>" role="button">Helps and Tutorials</a>
      </div>
    </div>

    <div class="container">
      <%= render @view_module, @view_template, assigns %>
    </div>

  </div>

  <!-- ***** Footer Area Start ***** -->
  <footer class="footer-social-icon text-center section_padding_70 clearfix">
    <!-- footer logo -->
    <div class="footer-text">
      <img src="<%= static_path(@conn, "/images/l1.png") %>" style="height: 50px;" alt="">
    </div>

    <div class="footer-menu">
      <nav>
        <ul>
          <li><a href="<%= terms_path(@conn, :index) %>">Terms &amp; Conditions</a></li>
          <li><a href="<%= privacy_path(@conn, :index) %>">Privacy Policy</a></li>
        </ul>
      </nav>
    </div>
    <!-- Foooter Text-->
    <div class="footer-info-block">
      <p class="footer-info">Texty Marketing is a 100% opt-in service. We do not provide lists of phone numbers nor do
        we access or share our users' contact lists.</p>
    </div>
    <div class="footer-info-block">
      <p class="footer-info">This website uses <a href="https://stripe.com"><img class="stripe-logo" src="<%= static_path(@conn, "/images/stripe_logo.png")
            %>" alt="Powered by Stripe."></a> which is most secure online payment system. And also protected by <a href="https://en.wikipedia.org/wiki/HTTPS"
          target="_blank">https</a></p>
      <p class="footer-info"></p>
    </div>
    <div class="copyright-text">
      <p>Copyright ©2018 Texty. Designed by <a href="https://www.welikeminimal.com" target="_blank">We like minimal.</a></p>
    </div>
  </footer>
  <!-- ***** Footer Area Start ***** -->

  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  <!--Start of Tawk.to Script-->
  <script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
      var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
      s1.async = true;
      s1.src = 'https://embed.tawk.to/5b96a874c666d426648aa016/default';
      s1.charset = 'UTF-8';
      s1.setAttribute('crossorigin', '*');
      s0.parentNode.insertBefore(s1, s0);
    })();
  </script>
  <!--End of Tawk.to Script-->
</body>

</html>